### ISSUE TITLE
this.c.compile is not a function

### ISSUE THREAD

**Issue by cdbkr** [deepsweet/mustache-loader#11]
Hello, I am receiving this error when using mustache-loader.

`this.c.compile is not a function
`

I believe problem is coming with #9 when including only the hogan.js/lib/template file.
Later on, line https://github.com/deepsweet/mustache-loader/blob/master/index.js#L61 you are passing the wrong compiler to Hogan.js, since the current H doesn't have any compiler in it (only exposed in the main file).

```
function (Hogan) {
  Hogan.Template = function (codeObj, text, compiler, options) {
```

```
var Hogan = require('./compiler');
Hogan.Template = require('./template').Template;
Hogan.template = Hogan.Template;
module.exports = Hogan;
```

```
return 'var H = require("hogan.js/lib/template");\n' +
           'module.exports = function() { ' +
           'var T = new H.Template(' +
           Hogan.compile(source, { asString: true }) +
           ', ' +
           JSON.stringify(source) +
           ', H);' + suffix;
```

**Comment by deepsweet** [comment]
sorry, reverted, should be ok now.
