### ISSUE TITLE
Using images in templates

### ISSUE THREAD

**Issue by koko236** [deepsweet/mustache-loader#13]
Let's say I have a template like this: 

template.mustache:
`<div><img src="../img/img1.png" alt=""></div>`

and file-loader setup in webpack config for all images. 

It seems that by default images referenced by templates are ignored by loaders. Should I wire the mustache-loader in some special way to make webpack take them into account?

**Comment by baderbuddy** [comment]
Later this week I should get a chance to try this out, but I'd think you'd use require to load the image instead of just the relative URL

**Comment by koko236** [comment]
I believe handlebars-template-loader does it by default with img relative paths (same as css-loader or html-loader) and handlebars-loader (another hb loader) can do it using inlineRequires option so for now I switched to the former. I'm not very experienced with Webpack and I thought it should be easy to chain loaders in some way to use a dedicated loader for images but apparently neither template loaders nor html-loader (which could take care of images) output raw html suitable for the next loader to digest.

**Comment by baderbuddy** [comment]
I'm still playing around with this, I'd of course welcome a pull request, I'd rather find a way to use the output of html-loader so that could be chained into mustache-loader, that way we're not recreating the wheel here.

I haven't quite found the solution yet, this weekend I should have some time to play with it more.

**Comment by baderbuddy** [comment]
Next release there should be a way to work with images.

**Comment by natiz** [comment]
So what's the recommended solution for using images in templates?

**Comment by baderbuddy** [comment]
@natiz you can chain other loaders. So if your template contains images or anything else that the HTML loader can handle you can chain the HTML loader between mustache and your template.

**Comment by rschaufler** [comment]
@baderbuddy do you have an working example for this? if i try chaining the html-loader, it won't compile

```
{
  test: /\.html$/,
  use: [
    {
      loader: 'mustache-loader'
    },
    {
      loader: 'html-loader',
      options: {
        interpolate: true
      }
    }
  ]
}
```

Error:

```
ERROR in   Error: /path/on/my/system/file.html?./node_modules/html-webpack-plugin/lib/loader.js:3
  window.Hogan = H;
  ^
  ReferenceError: window is not defined
```

I had no luck with that. If i only use the html-loader, it properly renders and fetches the images.

If i chain them in a different order, it also wont work:

```
{
  test: /\.html$/,
  use: [
    {
      loader: 'html-loader',
      options: {
        interpolate: true
      }
    },
    {
      loader: 'mustache-loader'
    }
  ]
}
```

Error:

```
ERROR in ./src/file.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/page.html)
    Module not found: Error: Can't resolve './\"./assets/1.jpg\"' in '/path/on/my/system'
```

**Comment by supersky07** [comment]
Webpack 4.30.0

below config can solve this.

```
{
    test: /\.mustache$/,
    use: [
        {
            loader: 'mustache-loader'
        },
        {
            loader: 'html-loader'
        }
    ]
}
```
