### ISSUE TITLE
Template text gets included twice

### ISSUE THREAD

**Issue by FarSeeing** [deepsweet/mustache-loader#20]
Template text gets included twice - first time as a code object and the second one as original template so it looks like this (beautified for readability):
```javascript
module.exports = function() {
    var T = new H.Template({
        code: function(c, p, i) {
            var t = this;
            t.b(i = i || "");
            t.b("<div><span>Some text</span></div>"); // First
            return t.fl();
        },
        partials: {},
        subs: {}
    }, "<div><span>Some text</span></div>", H); // Second
    return T.render.apply(T, arguments);
};
```
Can we just drop the second occurrence if `partials` and `subs` in compiled template are empty?

**Comment by baderbuddy** [comment]
If I get a chance I'll look into this. In the meantime I'd be happy to look at a pull request if you wanted to write the code.

**Comment by FarSeeing** [comment]
I have no idea how to solve that in general since just dropping template text will mangle the case when a template object is expected to be returned. Any ideas?

**Comment by FarSeeing** [comment]
Sorry for bothering but any updates on this?

**Comment by baderbuddy** [comment]
I have not had a chance to look into this yet. I should this weekend though

**Comment by baderbuddy** [comment]
I'm looking into this, but I haven't yet found a good way to handle it. If I had some better tests then I could try some things out, but my first priority is to not break this component for any users.

**Comment by FarSeeing** [comment]
What if we introduce some boolean option to (not) include the original text?

**Comment by baderbuddy** [comment]
I need a better test project, but I think it might be possible to completely eliminate the extra usage of the source. Let me try something out when I get a chance.

**Comment by FarSeeing** [comment]
I'm very sorry to ping you but any updates on this?
Many thanks in advance.

**Comment by baderbuddy** [comment]
Hi @FarSeeing  sorry it's taken me so long to respond. I think I might have a solution. I'm looking at the code some more and it might be possible to compile the hogan template at the client side, that should remove the need for the template getting sent twice. Could you try out the loader while chaining the html loader after it?

**Comment by FarSeeing** [comment]
@baderbuddy Hi. This solves the original issue but I'm aware it will hit the performance. Any ideas how to solve both issues?

**Comment by baderbuddy** [comment]
Hi @FarSeeing I added a couple of new optional parameters, one lets you do the compilation on the client side as we discussed, the other doesn't pass the template text into the Hogan Template compiler, I made it optional because it seems to work just fine for me, but I figure that parameter was there for a reason and I didn't want to break any existing usage. I'll probably release a new version tomorrow after I get more of a chance to test it out.

**Comment by FarSeeing** [comment]
Many thanks. Considering this issue to be fixed.
