### ISSUE TITLE
How do I pass variables?

### ISSUE THREAD

**Issue by markwoon** [deepsweet/mustache-loader#23]
I'm trying to use `mustache-loader` with `html-webpack-plugin`.

How can I pass the variables to use to render the template?  There's a reference to `arguments` at https://github.com/deepsweet/mustache-loader/blob/fef82c2c307e1a66c75c05827c93a99a65a99bfb/index.js#L44 but I don't see how to actually pass those arguments in.

**Comment by baderbuddy** [comment]
Markwoon, are you just looking for how to supply data to your templates?

In your code after you require a template then you can just call the returning function passing in the data.

**Comment by markwoon** [comment]
As mentioned, I'm using `mustache-loader` to send the result directly to `html-webpack-plugin`.  

There is no "my code".  I'd like a way to return the rendered result directly.  Is this possible?

**Comment by baderbuddy** [comment]
Thank you for clarifying. That is not something that this loader currently supports. Interesting enough doing something similar is what I was originally looking for when I found this loader. I would accept a PR for that kind of functionality.

**Comment by markwoon** [comment]
Done.

**Comment by baderbuddy** [comment]
Thank you very much for the PR. I've merged it in, and I'll do a release.
