### ISSUE TITLE
minify option - causes Webpack to stall when bundling

### ISSUE THREAD

**Issue by jonathanchrisp** [deepsweet/mustache-loader#6]
Hey @deepsweet,

I've found that if you specify the minify option, e.g. 
```
{
  test: /\.template$/,
  loader: 'mustache?minify'
}
```
It causes Webpack to stall when bundling. I've found removing this option resolves the problem. Please note that I installed the html-minifier and this didn't rectify the problem. Are you aware of this problem and if so do you know a way around it?

**Comment by deepsweet** [comment]
https://github.com/deepsweet/mustache-loader/issues/12

**Comment by baderbuddy** [comment]
I'll test this out and see if I can reproduce the issue. Do you have a link to your project that I could reference while trying to debug this?

**Comment by jonathanchrisp** [comment]
@baderbuddy Apologies but we've used this on a private project and I can't share the source.

**Comment by baderbuddy** [comment]
@jonathanchrisp I haven't been able to reproduce this issue.

**Comment by jonathanchrisp** [comment]
@baderbuddy - If you're unable to reproduce then I think we can close.
